name: SnowGlobe
version: 1.0
main: org.red.globe.SnowGlobePlugin
api-version: 1.19
authors: [ RedKiller ]
description: fuck

commands:
  snowGlobe:
    description: registerSnowGlobe
    aliases: [ sg, 스노우볼 ]
    permission: snowGlobe_snowGlobe
    permission-message: 당신은 이 명령어를 사용할 권한이 존재하지 않습니다!
  test:
    description: test command
    aliases: [ 테스트 ]
    permission: snowGlobe_test
    permission-message: 당신은 이 명령어를 사용할 권한이 존재하지 않습니다!


permissions:
  snowGlobe_snowGlobe:
    default: op
  snowGlobe_test:
    default: op
